### ISSUE TITLE
Solicitar país de origen

### ISSUE THREAD

**Issue by EntornosEdib** [EntornosEdib/Mensajes#4]
Crear una función o método que solicite el país de origen al usuario con un mensaje en la consola.
El método debe mostrar una lista de países con al menos 10 opciones distintas y permitir que el usuario elija uno de ellos.

El método debe devolver un argumento numérico de tipo entero con el código de país elegido. Por ejemplo, España (34), Reino Unido (44)
Se debe validar el valor entrado para impedir valores negativos o valor cero.

**Comment by squall722** [comment]
Trabajo finalizado. ruego revises
